---
- name: php | Add ppa repository
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: php | Update apt
  apt: update_cache=yes

- name: php | Install
  apt: pkg=php5 state=latest

- name: php | Install php5-fpm
  apt: pkg=php5-fpm state=latest

- name: php | Install PHP Packages
  apt: pkg={{ item }} state=latest
  with_items: php.packages
  when: php.packages is defined

- include: configure.yml
