---
- name: vagrant_local | Set the hostname in /etc/hostname
  shell: echo {{ vagrant_local.hostname }} > /etc/hostname
  when: vagrant_local.hostname is defined

- name: vagrant_local | Set the hostname
  shell: hostname {{ vagrant_local.hostname }}
  when: vagrant_local.hostname is defined

- name: vagrant_local | Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1 localhost {{ vagrant_local.hostname }}' owner=root group=root mode=0644
